apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pducmis7l-nodejs 
  janus-idp.io/tekton: pducmis7l-nodejs
  backstage.io/kubernetes-id: pducmis7l-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pducmis7l-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  